variable "vpcid" {}
variable "pub_sub1_cidr" {}
variable "pub_sub1_az" {}
variable "pub_sub2_cidr" {}
variable "pub_sub2_az" {}
variable "rt_destination_cidr" {}
variable "region" {}
variable "priv_sub1_cidr" {}
variable "priv_sub1_az" {}
variable "priv_sub2_cidr" {}
variable "priv_sub2_az" {}